services:
  minio:
    image: minio/minio:latest
    ports:
      - "${MINIO_PORT:-9000}:${MINIO_PORT:-9000}"
      - "${MINIO_CONSOLE_PORT:-9001}:${MINIO_CONSOLE_PORT:-9001}"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ADMIN}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server /data --address :${MINIO_PORT:-9000} --console-address :${MINIO_CONSOLE_PORT:-9001}
    entrypoint: >
      /bin/sh -c '
        isAlive() { curl -sf http://127.0.0.1:${MINIO_PORT:-9000}/minio/health/live; }
        minio $0 "$@" --quiet & echo $! > /tmp/minio.pid
        while ! isAlive; do sleep 0.1; done
        mc alias set minio http://127.0.0.1:${MINIO_PORT:-9000} ${MINIO_ADMIN} ${MINIO_PASSWORD}
        mc mb minio/${MINIO_BUCKET:-bucket} || true
        mc anonymous set public minio/${MINIO_BUCKET:-bucket}
        kill -s INT $(cat /tmp/minio.pid) && rm /tmp/minio.pid
        while isAlive; do sleep 0.1; done
        exec minio $0 "$@"
      '

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=1G
